kind: pipeline
name: default

steps:
- name: publish
  image: appleboy/drone-ssh
  settings:
    host: eban.eu.org
    username: git
    password: 
      from_secret: ssh_passwd
    port: 22
    script:
      - bash /opt/publish.sh
  when:
    branch:
      - master
    event:
      exclude:
      - pull_request

- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id: 
      from_secret: discord-webhook-id
    webhook_token: 
      from_secret: discord-webhook-token
    message: >
      {{#success build.status}}
        Build #{{build.number}} of {{repo.name}} succeeded. 🎉
      {{else}}
        Build #{{build.number}}  {{commit.message}} of {{repo.name}} failed. 😭
      {{/success}}            