variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-builder

stages:
  - test
  - build & publish

test-job:      
  stage: test
  script:
    - pelican -o /tmp --fatal warnings

build-job: 
  stage: build & publish  
  script:
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_EBANVM01_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - pelican 
    - rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" output/ deploy@vm01.eban.eu.org:/var/www/ilearned-en
  only:
  - master
