variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
    image: frolvlad/alpine-python3

    before_script:
        - apk add openssh git
        - git submodule update --recursive --remote
        - pip install pelican bs4 Markdown pelican-minify

stages:
  - test
  - build & publish

test-job:      
  stage: test
  script:
    - pelican -o /tmp --fatal warnings

build-job: 
  stage: build & publish  
  script:
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_EBANVM01_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - pelican 
    - scp -r -i ~/.ssh/id_ed25519 output/* deploy@vm01.eban.eu.org:ilearned
