default:
    image: hub.ilearned.eu/i-learned/ci-cd/blog-builder
    tags:
        - AMD64

stages:
    - lint
    - test
    - test-deploy
    - prod-deploy

prettier:
    stage: lint
    allow_failure: true
    script:
        - rm -rf ./..?* ./.[!.]* ./*
        - git clone https://gitlab.ilearned.eu/i-learned/blog/theme -b $CI_COMMIT_REF_NAME . --recursive
        - git submodule update --recursive --remote
        - prettier . -w
        - git add .
        - git commit -m "[🧹 Lint] Linted code and updated submodule"
        - git push https://CI_CD:$CI_GIT_USER_PASSWD@gitlab.ilearned.eu/i-learned/blog/theme/
    only:
        - master

test-job:
    stage: test
    script:
        - pip install -r requirements.txt
        - make build
    artifacts:
        paths:
            - output/

prod-deploy-job:
    stage: prod-deploy
    script:
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - echo "$SSH_EBANVM01_PRIVATE_KEY" > ~/.ssh/id_ed25519
        - chmod 600 ~/.ssh/id_ed25519
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" output/ deploy@vm01.eban.eu.org:/var/www/ilearned-blog
    dependencies:
        - test-job
    only:
        - master

test-deploy-job:
    stage: test-deploy
    script:
        - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir output
    dependencies:
        - test-job
    only:
        - merge_requests
