default:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-builder
    before_script:
        - rm -rf ./..?* ./.[!.]* ./*
        - git clone https://gitlab.ilearned.eu/i-learned/blog/theme -b $CI_COMMIT_REF_NAME . --recursive
        - git submodule update --recursive --remote
    tags:
        - AMD64

stages:
    - lint
    - test
    - lighthouse
    - test-deploy
    - prod-deploy

lint-job:
    image: node:latest
    stage: lint
    allow_failure: true
    script:
        - npm install -g prettier
        - prettier . -w
        - git config --global user.email "contact@ilearned.eu"
        - git config --global user.name "Gitlab CI"
        - git add .
        - git commit -m "[🧹 Lint] Linted code and updated submodule"
        - git push https://CI_CD:$CI_GIT_USER_PASSWD@gitlab.ilearned.eu/i-learned/blog/theme/
    only:
        - master

test-job:
    stage: test
    script:
        - pelican -o /tmp --fatal warnings
        - sh build.sh

lighthouse-job:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-chrome95-ff94
    stage: lighthouse
    script:
    - sh build.sh
    - npm install -g @lhci/cli@0.8.x
    - lhci autorun --upload.target=temporary-public-storage --collect.settings.chromeFlags="--no-sandbox" || echo "LHCI failed!"
    - cd .lighthouseci
    - cat links.json

    
prod-deploy-job:
    stage: prod-deploy
    script:
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - echo "$SSH_EBANVM01_PRIVATE_KEY" > ~/.ssh/id_ed25519
        - chmod 600 ~/.ssh/id_ed25519
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - sh build.sh
        - rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" output/ deploy@vm01.eban.eu.org:/var/www/ilearned
        - rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" en/ deploy@vm01.eban.eu.org:/var/www/ilearned-en
    only:
        - master

test-deploy-job:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-builder-dev
    stage: test-deploy
    script:
        - sh build.sh
        - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir output
    only:
        - merge_requests
